name: Skymu for Mac Legacy/Xamarin

on:
  push:
    branches: [ "xamarin" ]
  pull_request:
    branches: [ "xamarin" ]

jobs:
  build:
    runs-on: macos-15-intel # macOS 26 runners do not include Xamarin.Mac framework needed by setup-xamarin.
    env:
      Solution_Name: SkymuMacLegacy.sln
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Xamarin
      uses: maxim-lobanov/setup-xamarin@v1
      with:
        xamarin-mac-version: 6
    - name: And upload :3
      uses: actions/upload-artifact@v7
      with:
        path: 'SkymuMac/bin/'
        retention-days: 7
        archive: true
